"""LDA-based distance classification helpers.

This module provides utilities to benchmark linear discriminant analysis
on pairwise distance features.  Two preprocessing strategies are
supported:

``SelectKBest``
    Standardises the input features and selects the top ``k`` distance
    features according to mutual information before fitting LDA.

``PCA98``
    Standardises the input features, applies PCA retaining 98% of the
    variance and then fits LDA on the resulting components.

The :func:`run_lda_experiments` function expects a directory structure
similar to the one generated by the existing FIT pipelines: for each
species there should be ``cv_results/all_folds.csv`` containing
cross-validation pairs and ``test_pairs/<species>_pairs.csv`` containing
held-out comparisons.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable, List, Tuple

import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.feature_selection import SelectKBest, mutual_info_classif
from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import GridSearchCV, PredefinedSplit
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

__all__ = ["build_pipeline", "run_lda_experiments"]


def build_pipeline(method: str, dist_cols: Iterable[str]) -> Tuple[Pipeline, List[dict]]:
    """Return a configured pipeline and parameter grid for LDA."""

    if method == "SelectKBest":
        pipe = Pipeline(
            [
                ("scaler", StandardScaler()),
                ("select", SelectKBest(mutual_info_classif)),
                ("model", LinearDiscriminantAnalysis()),
            ]
        )
        param_grid = [
            {
                "select__k": list(range(1, len(list(dist_cols)) + 1)),
                "model__solver": ["svd"],
                "model__shrinkage": [None],
            },
            {
                "select__k": list(range(1, len(list(dist_cols)) + 1)),
                "model__solver": ["lsqr"],
                "model__shrinkage": [None, 0.1, 0.5, 0.9],
            },
        ]
        return pipe, param_grid

    if method == "PCA98":
        pipe = Pipeline(
            [
                ("scaler", StandardScaler()),
                ("pca", PCA(n_components=0.98)),
                ("model", LinearDiscriminantAnalysis()),
            ]
        )
        param_grid = [
            {
                "model__solver": ["svd"],
                "model__shrinkage": [None],
            },
            {
                "model__solver": ["lsqr"],
                "model__shrinkage": [None, 0.1, 0.5, 0.9],
            },
        ]
        return pipe, param_grid

    raise ValueError(f"Unknown method: {method}")


def _load_distance_data(cv_csv: Path, tp_csv: Path) -> Tuple[pd.DataFrame, pd.DataFrame, List[str]]:
    """Load and prepare distance feature data for a species."""

    df_cv = pd.read_csv(cv_csv)
    df_tp = pd.read_csv(tp_csv)

    df_cv = df_cv[
        ~(
            df_cv["trail_a_id"].str.strip().eq("unknown")
            | df_cv["trail_b_id"].str.strip().eq("unknown")
        )
    ]
    df_tp = df_tp[
        ~(
            df_tp["trail_a_id"].str.strip().eq("unknown")
            | df_tp["trail_b_id"].str.strip().eq("unknown")
        )
    ]

    dist_cols = [
        c
        for c in df_cv.columns
        if c.startswith(("dist_", "mean_", "median_", "min_", "max_"))
    ]
    if not dist_cols:
        raise ValueError("No distance features available")

    df_cv = df_cv.dropna(subset=dist_cols)
    df_tp = df_tp.dropna(subset=dist_cols)
    return df_cv, df_tp, dist_cols


def run_lda_experiments(base_dir: Path, out_base_dir: Path) -> None:
    """Run LDA experiments for all species contained in ``base_dir``.

    For each species directory two CSV files are expected as described in
    the module level documentation.  For every species the function writes
    a ``lda_selectk_vs_pca98.csv`` with the achieved balanced
    accuracies and, when applicable, the selected distance features.
    """

    base_dir = Path(base_dir)
    out_base_dir = Path(out_base_dir)

    for sp_dir in sorted(base_dir.iterdir()):
        if not sp_dir.is_dir():
            continue
        species = sp_dir.name

        cv_csv = out_base_dir / species / "cv_results" / "all_folds.csv"
        tp_csv = out_base_dir / species / "test_pairs" / f"{species}_pairs.csv"
        if not (cv_csv.exists() and tp_csv.exists()):
            print(f"⚠️ Missing data for {species}, skipping")
            continue

        try:
            df_cv, df_tp, dist_cols = _load_distance_data(cv_csv, tp_csv)
        except ValueError as exc:
            print(f"⚠️ {exc} for {species}, skipping")
            continue

        X_cv = df_cv[dist_cols].to_numpy()
        y_cv = df_cv["same_individual"].map({True: 1, False: 0}).to_numpy()
        ps = PredefinedSplit(test_fold=df_cv["fold"].to_numpy())

        X_test = df_tp[dist_cols].to_numpy()
        y_test = df_tp["same_individual"].map({True: 1, False: 0}).to_numpy()

        results: List[dict] = []
        for method in ["SelectKBest", "PCA98"]:
            pipe, param_grid = build_pipeline(method, dist_cols)
            gs = GridSearchCV(
                pipe,
                param_grid,
                scoring="balanced_accuracy",
                cv=ps,
                refit=True,
                n_jobs=-1,
                verbose=0,
            )
            gs.fit(X_cv, y_cv)

            model = gs.best_estimator_
            cv_score = balanced_accuracy_score(y_cv, model.predict(X_cv))
            test_score = balanced_accuracy_score(y_test, model.predict(X_test))

            result = {
                "species": species,
                "method": method,
                "cv_bal_acc": round(float(cv_score), 3),
                "test_bal_acc": round(float(test_score), 3),
            }

            if method == "SelectKBest":
                k = model.named_steps["select"].k
                feats = np.array(dist_cols)[
                    model.named_steps["select"].get_support()
                ].tolist()
                result["best_k"] = k
                result["top_features"] = ";".join(feats)

            results.append(result)

        out_file = out_base_dir / species / "lda_selectk_vs_pca98.csv"
        out_file.parent.mkdir(parents=True, exist_ok=True)
        pd.DataFrame(results).to_csv(out_file, index=False)

        print(f"✅ Finished {species}, results stored in {out_file}")
